//! Generate typed Rowan views from the node declarations in `blossom.ungram`.
use crate::util;
use std::{fs, path::Path, process::ExitCode};

/// Generator options.
#[derive(Debug, clap::Args)]
pub struct Args {
    /// Verify the checked-in output rather than writing it.
    #[arg(long)]
    pub check: bool,
}

/// Generate or check the typed AST.
pub fn run(args: Args) -> ExitCode {
    let root = util::workspace_root();
    let grammar = root.join("crates/blossom-syntax/blossom.ungram");
    let output = root.join("crates/blossom-syntax/src/ast/generated.rs");
    match generate(&grammar) {
        Ok(source) => {
            if args.check {
                match fs::read_to_string(&output) {
                    Ok(existing) if existing == source => {
                        println!("gen-ast: up to date");
                        ExitCode::SUCCESS
                    }
                    Ok(_) => util::fail("gen-ast", "generated.rs differs from blossom.ungram"),
                    Err(err) => util::fail("gen-ast", err),
                }
            } else {
                if let Some(dir) = output.parent()
                    && let Err(err) = fs::create_dir_all(dir)
                {
                    return util::fail("gen-ast", err);
                }
                match fs::write(&output, source) {
                    Ok(()) => {
                        println!("gen-ast: wrote {}", output.display());
                        ExitCode::SUCCESS
                    }
                    Err(err) => util::fail("gen-ast", err),
                }
            }
        }
        Err(err) => util::fail("gen-ast", err),
    }
}
fn generate(path: &Path) -> Result<String, String> {
    let grammar = fs::read_to_string(path).map_err(|e| e.to_string())?;
    let mut nodes = Vec::new();
    for line in grammar.lines() {
        let line = line.trim();
        if line.starts_with("//") || line.is_empty() {
            continue;
        }
        let (name, _) = line
            .split_once(" = ")
            .ok_or_else(|| format!("expected `Node = Rule`: {line}"))?;
        if !name.chars().next().is_some_and(|c| c.is_ascii_uppercase())
            || !name.chars().all(|c| c.is_ascii_alphanumeric())
        {
            return Err(format!("invalid node name: {name}"));
        }
        if nodes.contains(&name) {
            return Err(format!("duplicate node: {name}"));
        }
        nodes.push(name);
    }
    for required in ["SourceFile", "Item", "Stmt", "Literal", "Expr"] {
        if !nodes.contains(&required) {
            return Err(format!("missing {required}"));
        }
    }
    let mut out = String::from(
        "// @generated by cargo xtask gen-ast from blossom.ungram; do not edit.\nuse crate::{SyntaxKind, SyntaxNode};\nuse super::{AstNode, AstChildren, child, children};\n\n",
    );
    for name in &nodes {
        if ["Item", "Stmt", "Literal", "Expr"].contains(name) {
            continue;
        }
        let kind = uppercase(name);
        out.push_str(&format!("/// Typed CST view for `{name}`.\n#[derive(Debug, Clone, PartialEq, Eq)]\npub struct {name}(pub(crate) SyntaxNode);\nimpl AstNode for {name} {{\n    fn can_cast(kind: SyntaxKind) -> bool {{ kind == SyntaxKind::{kind} }}\n    fn cast(node: SyntaxNode) -> Option<Self> {{ Self::can_cast(node.kind()).then_some(Self(node)) }}\n    fn syntax(&self) -> &SyntaxNode {{ &self.0 }}\n}}\n"));
        // Uniform typed accessors make the full generated tree traversable, including on broken input.
        out.push_str(&format!("impl {name} {{\n    /// Direct named child, if present.\n    pub fn name(&self) -> Option<Name> {{ child(&self.0) }}\n    /// Direct expressions.\n    pub fn exprs(&self) -> AstChildren<Expr> {{ children(&self.0) }}\n    /// Direct types.\n    pub fn types(&self) -> AstChildren<Type> {{ children(&self.0) }}\n}}\n\n"));
    }
    let groups: [(&str, &[&str]); 4] = [
        ("Stmt", &["VerbStmt", "IfStmt", "ForStmt"]),
        (
            "Literal",
            &[
                "NotLit",
                "LetLit",
                "OuterLit",
                "InsertedLit",
                "DeletedLit",
                "SealedLit",
                "FinalLit",
                "PerLit",
                "AnyLit",
                "ForallLit",
                "EverLit",
                "SentLit",
                "QuorumLit",
                "AtomLit",
            ],
        ),
        (
            "Expr",
            &[
                "LiteralExpr",
                "PathExpr",
                "CallExpr",
                "MethodCallExpr",
                "BangCallExpr",
                "FieldExpr",
                "TupleIndexExpr",
                "IndexExpr",
                "BinaryExpr",
                "PrefixExpr",
                "CastExpr",
                "ParenExpr",
                "TupleExpr",
                "VecExpr",
                "SetExpr",
                "MapExpr",
                "FoldExpr",
                "IfExpr",
                "MatchExpr",
                "StructLitExpr",
                "ClosureExpr",
                "Wildcard",
                "SelfExpr",
            ],
        ),
        (
            "Item",
            &[
                "UseItem",
                "ImportItem",
                "IncludeItem",
                "ConstItem",
                "ParamItem",
                "TypeAlias",
                "StructItem",
                "EnumItem",
                "FnItem",
                "ExternItem",
                "ImplItem",
                "LatticeTypeItem",
                "AggregateItem",
                "ServiceItem",
                "ModuleItem",
                "ProtocolItem",
                "RoleItem",
                "AtSection",
                "InterposeItem",
                "BlockItem",
                "OverrideItem",
                "AclItem",
                "RelDecl",
                "CellDecl",
                "TimerDecl",
                "ViewDecl",
                "HandlerItem",
                "BootstrapItem",
                "FactItem",
                "InvariantItem",
                "MigrateItem",
                "TranslateItem",
                "SnapshotItem",
                "SpecItem",
            ],
        ),
    ];
    for (group, variants) in groups {
        for name in variants {
            if !nodes.contains(name) {
                return Err(format!("{group} variant {name} is not in grammar"));
            }
        }
        out.push_str(&format!(
            "/// A {group} variant.\n#[derive(Debug, Clone, PartialEq, Eq)]\npub enum {group} {{\n"
        ));
        for name in variants {
            out.push_str(&format!("    /// `{name}`.\n    {}({name}),\n", variant(group, name)));
        }
        out.push_str("}\n");
        out.push_str(&format!(
            "impl AstNode for {group} {{\n    fn can_cast(kind: SyntaxKind) -> bool {{ matches!(kind, "
        ));
        for (i, name) in variants.iter().enumerate() {
            if i > 0 {
                out.push_str(" | ");
            }
            out.push_str(&format!("SyntaxKind::{}", uppercase(name)));
        }
        out.push_str(") }\n    fn cast(node: SyntaxNode) -> Option<Self> { match node.kind() {\n");
        for name in variants {
            out.push_str(&format!(
                "        SyntaxKind::{} => Some(Self::{}({name}(node))),\n",
                uppercase(name),
                variant(group, name)
            ));
        }
        out.push_str("        _ => None,\n    }}\n    fn syntax(&self) -> &SyntaxNode { match self {\n");
        for name in variants {
            out.push_str(&format!("        Self::{}(n) => n.syntax(),\n", variant(group, name)));
        }
        out.push_str("    }}\n}\n\n");
    }
    let mut child = std::process::Command::new("rustfmt")
        .args(["--emit", "stdout", "--edition", "2024"])
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .spawn()
        .map_err(|e| e.to_string())?;
    use std::io::Write;
    child
        .stdin
        .take()
        .ok_or("rustfmt stdin unavailable")?
        .write_all(out.as_bytes())
        .map_err(|e| e.to_string())?;
    let output = child.wait_with_output().map_err(|e| e.to_string())?;
    if !output.status.success() {
        return Err("rustfmt failed on generated AST".to_string());
    }
    String::from_utf8(output.stdout).map_err(|e| e.to_string())
}
fn uppercase(s: &str) -> String {
    s.chars().flat_map(char::to_uppercase).collect()
}

fn variant<'a>(group: &str, name: &'a str) -> &'a str {
    if group == "Item" && name == "AtSection" {
        return "At";
    }
    if group == "Expr" && name == "SelfExpr" {
        return "SelfValue";
    }
    if group == "Literal" && name == "AtomLit" {
        return "Plain";
    }
    if group == "Item" {
        name.strip_suffix("Item")
            .or_else(|| name.strip_suffix("Decl"))
            .unwrap_or(name)
    } else if group == "Stmt" {
        name.strip_suffix("Stmt").unwrap_or(name)
    } else if group == "Literal" {
        name.strip_suffix("Lit").unwrap_or(name)
    } else {
        name.strip_suffix("Expr").unwrap_or(name)
    }
}
