#!/usr/bin/env bash
# Builds a shared example app (examples/web/APP.bls) as Cloudflare Durable Objects for local runs
# (docs/design/DURABLE-OBJECTS.md, docs/design/KEYED.md §4), into do/build/APP: the node's WebAssembly
# (crates/blossom-do), the page (scripts/build-web.sh's output), the app's sources and deployment, an entry module over
# do/src/worker.js, and its wrangler config. ROLE is the role of the deployment's one node, `s` (default `Server`; a
# keyed role makes `s` the host of its members, each an object of its own). Then:
#
#   cd do && npx wrangler dev --config build/APP/wrangler.toml --port 8787   # workerd here; nothing is deployed
#
# and open http://localhost:8787/ (for a keyed role, /?member=NAME) in two tabs. The deployment's seed is the Worker's
# secret BLOSSOM_SEED: do/APP.dev.vars keeps it (made on the first build), so storage outlives rebuilds.
set -euo pipefail
cd "$(dirname "$0")/.."
app="${1:?usage: scripts/build-do.sh APP [ROLE] (APP: polls, board, tictactoe, pixels, rooms Room, chat, todos_shared)}"
role="${2:-Server}"
src="examples/web/$app.bls"
[ -f "$src" ] || { echo "build-do: no $src" >&2; exit 2; }
export PATH="$PWD/.tools/bin:$PATH"
[ -f web/pkg-member/blossom_web_bg.wasm ] || scripts/build-web.sh
cargo build -q -p blossom-do --target wasm32-unknown-unknown --release
wasm="${CARGO_TARGET_DIR:-target}/wasm32-unknown-unknown/release/blossom_do.wasm"
out="do/build/$app"
rm -rf "$out"
mkdir -p "$out/public"
wasm-bindgen --target web --no-typescript --out-dir "$out/pkg" "$wasm"
cp web/index.html web/host.js web/host.css web/apps.css web/todomvc.css web/chat.css "$out/public/"
cp -R web/pkg-member "$out/public/pkg-member"
vars="do/$app.dev.vars"
[ -f "$vars" ] || echo "BLOSSOM_SEED=$(openssl rand -hex 16)" > "$vars"
cp "$vars" "$out/.dev.vars"
# The program's sources, its deployment (one node, `s`), and its stylesheet.
version="$(sed -n 's/^program [A-Za-z_][A-Za-z0-9_]* version \([0-9]*\);.*/\1/p' "$src" | head -1)"
[ -n "$version" ] || { echo "build-do: $src has no \`program NAME version N;\` line" >&2; exit 2; }
node - "$app" "$version" "$role" "$out" <<'JS'
const fs = require("fs");
const [app, version, role, out] = process.argv.slice(2);
const dir = "examples/web";
const files = {};
for (const f of [`${app}.bls`, "ui.bls", "events.bls"]) files[f] = fs.readFileSync(`${dir}/${f}`, "utf8");
const deploy = [
  "format = 1",
  "[deployment]",
  `id = "${app}-object"`,
  `program = "${app}"`,
  `version = ${version}`,
  `source = "${app}.bls"`,
  "[[node]]",
  'name = "s"',
  `role = "${role}"`,
  'addr = "127.0.0.1:1"',
  `principal = "spiffe://object/${app}/${role}/s"`,
  "[security]",
  'mode = "insecure-dev"',
  "[storage]",
  'data_dir = "data"',
  "",
].join("\n");
const css = `${dir}/${app}.css`;
const style = fs.existsSync(css)
  ? fs.readFileSync(css, "utf8").replace('@import url("/apps.css");', fs.readFileSync("web/apps.css", "utf8"))
  : null;
fs.writeFileSync(
  `${out}/app.js`,
  `// Generated by scripts/build-do.sh for ${app}.\nexport default ${JSON.stringify({ files, deploy, node: "s", style }, null, 1)};\n`,
);
fs.writeFileSync(
  `${out}/entry.js`,
  [
    `// Generated by scripts/build-do.sh for ${app}: the object class and the Worker of do/src/worker.js.`,
    'import { DoNode, DoSite, mintToken, initSync } from "./pkg/blossom_do.js";',
    'import wasm from "./pkg/blossom_do_bg.wasm";',
    'import app from "./app.js";',
    'import { blossom } from "../../src/worker.js";',
    "",
    "initSync({ module: wasm });",
    "const made = blossom(app, { DoNode, DoSite, mintToken });",
    "export const BlossomObject = made.BlossomObject;",
    "export default made.worker;",
    "",
  ].join("\n"),
);
fs.writeFileSync(
  `${out}/wrangler.toml`,
  [
    `# Generated by scripts/build-do.sh for ${app} (docs/design/DURABLE-OBJECTS.md): run locally with`,
    `#   cd do && npx wrangler dev --config build/${app}/wrangler.toml`,
    `name = "blossom-${app.replace(/_/g, "-")}"`,
    'main = "entry.js"',
    'compatibility_date = "2026-09-01"',
    "",
    "# The page: the browser host and its engine (scripts/build-web.sh).",
    "[assets]",
    'directory = "./public"',
    'binding = "ASSETS"',
    "",
    "[[durable_objects.bindings]]",
    'name = "OBJECTS"',
    'class_name = "BlossomObject"',
    "",
    "[[migrations]]",
    'tag = "v1"',
    'new_sqlite_classes = ["BlossomObject"]',
    "",
    "# The node's WebAssembly, imported as a compiled module.",
    "[[rules]]",
    'type = "CompiledWasm"',
    'globs = ["**/*.wasm"]',
    "fallthrough = true",
    "",
  ].join("\n"),
);
JS
echo "built $out ($(du -h "$out/pkg/blossom_do_bg.wasm" | cut -f1) wasm): cd do && npx wrangler dev --config build/$app/wrangler.toml --port 8787"
