#!/usr/bin/env bash
# Builds a shared example app (examples/web/APP.bls) as a Cloudflare Durable Object for local runs
# (docs/design/DURABLE-OBJECTS.md): the node's WebAssembly (crates/blossom-do) into do/build/pkg, the page
# (scripts/build-web.sh's output) into do/public, and the app's sources and deployment into do/build/app.js. Then:
#
#   cd do && npx wrangler dev --port 8787        # workerd on this machine; nothing is deployed
#
# and open http://localhost:8787/ in two tabs.
set -euo pipefail
cd "$(dirname "$0")/.."
app="${1:?usage: scripts/build-do.sh APP (polls, board, tictactoe, pixels, chat, todos_shared)}"
src="examples/web/$app.bls"
[ -f "$src" ] || { echo "build-do: no $src" >&2; exit 2; }
export PATH="$PWD/.tools/bin:$PATH"
[ -f web/pkg-member/blossom_web_bg.wasm ] || scripts/build-web.sh
cargo build -q -p blossom-do --target wasm32-unknown-unknown --release
wasm="${CARGO_TARGET_DIR:-target}/wasm32-unknown-unknown/release/blossom_do.wasm"
rm -rf do/build do/public
wasm-bindgen --target web --no-typescript --out-dir do/build/pkg "$wasm"
mkdir -p do/public
cp web/index.html web/host.js web/host.css web/apps.css web/todomvc.css web/chat.css do/public/
cp -R web/pkg-member do/public/pkg-member
# The program's sources, its deployment (one server node, `s`), and its stylesheet.
version="$(sed -n 's/^program [A-Za-z_][A-Za-z0-9_]* version \([0-9]*\);.*/\1/p' "$src" | head -1)"
[ -n "$version" ] || { echo "build-do: $src has no \`program NAME version N;\` line" >&2; exit 2; }
node - "$app" "$version" <<'JS'
const fs = require("fs");
const [app, version] = process.argv.slice(2);
const dir = "examples/web";
const files = {};
for (const f of [`${app}.bls`, "ui.bls", "events.bls"]) files[f] = fs.readFileSync(`${dir}/${f}`, "utf8");
const deploy = [
  "format = 1",
  "[deployment]",
  `id = "${app}-object"`,
  `program = "${app}"`,
  `version = ${version}`,
  `source = "${app}.bls"`,
  "[[node]]",
  'name = "s"',
  'role = "Server"',
  'addr = "127.0.0.1:1"',
  `principal = "spiffe://object/${app}/Server/s"`,
  "[security]",
  'mode = "insecure-dev"',
  "[storage]",
  'data_dir = "data"',
  "",
].join("\n");
const css = `${dir}/${app}.css`;
const style = fs.existsSync(css)
  ? fs.readFileSync(css, "utf8").replace('@import url("/apps.css");', fs.readFileSync("web/apps.css", "utf8"))
  : null;
fs.writeFileSync(
  "do/build/app.js",
  `// Generated by scripts/build-do.sh for ${app}.\nexport default ${JSON.stringify({ files, deploy, node: "s", style }, null, 1)};\n`,
);
JS
echo "built do/ for $app ($(du -h do/build/pkg/blossom_do_bg.wasm | cut -f1) wasm): cd do && npx wrangler dev --port 8787"
